image: purifyyourhome/gitlab-mirror-to-github

stages:
        - deploy

deploy to production:
        stage: deploy
        environment: production
        only:
                - master
        script: git-push git@github.com:purifyyourhome/gitlab-mirror-to-github
